import clsx from 'clsx'
import './globals.css'
import type { Metadata } from 'next'
import { Rajdhani, Roboto, Poppins } from 'next/font/google'
import { MainNav } from '@/components/layout/main-nav'
import Footer from '@/components/layout/footer'
import { Button } from '@/components/ui/button'
import { mdiTwitter, mdiYoutube, mdiInstagram, mdiArrowUp, mdiAccountOutline, mdiCart, mdiCartOutline } from '@mdi/js';
import Icon from "@mdi/react";

const rajdhani = Rajdhani({
  subsets: ['latin'],
  style: 'normal',
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-rajdhani'
})

const roboto = Roboto({
  subsets: ['latin'],
  style: 'normal',
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto'
})

const poppins = Poppins({
  subsets: ['latin'],
  style: 'normal',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const mainNav = [
  {
    title: "Home",
    href: "/",
  },
  {
    title: "Servers",
    href: "/servers",
    disabled: true,
  },
  {
    title: "Leaderboards",
    href: "/leaderboards",
    disabled: true,
  },
  {
    title: "Clans",
    href: "/clans",
    disabled: true,
  },
  {
    title: "Maps",
    href: "/maps",
    disabled: true,
  },
  {
    title: "Store",
    href: "/store",
    disabled: true,
  },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(rajdhani.variable, roboto.variable, poppins.variable)}>
        <div className="absolute z-20 w-full border-b border-white/10">
          <div className="container h-28 flex items-center justify-between">
            <MainNav items={mainNav} />
            <Button
              size={"default"}
              className=""
            >
              <Icon path={mdiAccountOutline}
                size={0.8}
                color="white"
                className="mr-1 font-poppins"
              />
              Login
            </Button>
          </div>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
