import clsx from 'clsx'
import './globals.css'
import type { Metadata } from 'next'
import { Rajdhani, Roboto } from 'next/font/google'

const rajdhani = Rajdhani({
  subsets: ['latin'],
  style: 'normal',
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-rajdhani'
})

const roboto = Roboto({
  subsets: ['latin'],
  style: 'normal',
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(rajdhani.className/* , roboto.className */)}>{children}</body>
    </html>
  )
}
